--- #YAML:1.0
name:               AnyEvent-Callback
version:            0.03
abstract:           callback aggregator for L<AnyEvent> watchers.
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    bugtracker:  https://github.com/unera/libanyevent-callback/issues
    homepage:    https://github.com/unera/libanyevent-callback
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
